// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc1073.robot16.commands;

import org.usfirst.frc1073.robot16.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class NavDriver extends Command {
	//Decides which method execute will work through
	int defenseID;
	
	//False is 1st, true is 2nd
	boolean stage; 
	
	//TODO Needs to be calibrated, describes the aggression of drive correction algorithm
	final double k = 1.0;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public NavDriver(int defenseID, boolean stage) {
		//Saves defenseID for this instance
		this.defenseID = defenseID;
		this.stage = stage;
		
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.navigation);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		if(stage == false){Robot.navigation.driveConfig();}
		if(stage){Robot.navigation.driveConfigStage2();}
	}
	

	// Called repeatedly when this Command is scheduled to run
	protected void execute(){
		if(stage == false){Robot.navigation.defenseApproach(defenseID);}
		if(stage){Robot.navigation.postDefenseNavigation();}
	}
	
	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return Robot.navigation.areWeThereYet();
	}

	// Called once after isFinished returns true
	protected void end() {
		//Momentarily stops the motors
		Robot.driveTrain.getDriveCommand().movePID(0,0);
		
		if(stage == false){new NavDriver(defenseID,true);}
		
		//Executes the last stage directional orientation
		if(defenseID >= 0){Robot.navigation.finalConfig();}
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		//Stops motors prior to releasing control
		Robot.driveTrain.getDriveCommand().movePID(0, 0);
	}
}
