// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot16.subsystems;

import org.usfirst.frc1073.robot16.Robot;
import org.usfirst.frc1073.robot16.RobotMap;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Collector extends Subsystem implements PIDSubsystem{

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController rollerMotor = RobotMap.collectorrollerMotor;
    private final SpeedController elevationMotor = RobotMap.collectorelevationMotor;
    private final DigitalInput ballSensor = RobotMap.collectorballSensor;
    private final Solenoid armExtension = RobotMap.collectorarmExtension;
    private final Encoder elevationEncoder = RobotMap.collectorelevationEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    private final int ENCODER_TICS_TO_DEGREES = 1; // Hold place value... I think...
    private final double TOP_LIMIT = 90; // Top collector limit (in degrees)
    private final double BOTTOM_LIMIT = 0; // Bottom collector limit (in degrees)
    
    private double rollerSpeed = Robot.rollerSpeed;
    private double elevationSpeed = Robot.collectorElevationSpeed;
    
	/**************************
	 * 
	 * Method to role into the
	 * robot
	 * 
	 **************************/
	public void rollerIn() {
		if(Robot.invertRoller) rollerMotor.set(-rollerSpeed);
		else rollerMotor.set(rollerSpeed);
	}
	
	/**************************
	 * 
	 * Method to purge the ball
	 * out of the robot
	 * 
	 **************************/
	public void rollerPurge() {
		if(Robot.invertRoller) rollerMotor.set(rollerSpeed);
		else rollerMotor.set(-rollerSpeed);
	}
	
	/*****************************
	 * 
	 * Method to turn rollers off
	 * 
	 *****************************/
	public void rollerOff() {
		rollerMotor.set(0);
	}
	
	/*******************************
	 * 
	 * Manual control to rotate up
	 * 
	 *******************************/
	public void collectorUp() {
		if(Robot.invertElevation) elevationMotor.set(-elevationSpeed);
		else elevationMotor.set(elevationSpeed);
	}
	
	/*********************************
	 * 
	 * Manual control to rotate down
	 * 
	 *********************************/
	public void collectorDown() {
		if(Robot.invertElevation) elevationMotor.set(elevationSpeed);
		else elevationMotor.set(-elevationSpeed);
	}
	
	/**********************************
	 * 
	 * Method to toggles arm in or out
	 * 
	 **********************************/
	public void toggleArmExtension() {
		armExtension.set(!armExtension.get());
	}
	
	/*******************************
	 * 
	 * Gets the angle of collector
	 * 
	 * @return angle (in degrees)
	 * 
	 *******************************/
	public double getAngle(){
		return elevationEncoder.get();
	}
	
	/****************************************
	 * 
	 * Returns when a ball is in the robot.
	 * 
	 * @return true if ball is in the robot
	 *	else false
	 *
	 ****************************************/
	public boolean isLoaded(){
		return ballSensor.get();
	}
	
	@Override
	public double getPIDSource(int marker) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void setPIDOutput(double output, int marker) {
		// TODO Auto-generated method stub
		
	}
	
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

}

